#!/usr/bin/env python3

import copy
import json
import sys
import unidiff

def hunk_to_d(h):
    d = copy.deepcopy(h.__dict__)
    d["source"] = h.source
    d["target"] = h.target
    return d

def patch_to_d(p):
    d = copy.deepcopy(p.__dict__)
    d["hunks"] = [hunk_to_d(h) for h in p]
    return d


patch_set = unidiff.PatchSet(sys.stdin.read())
o = [patch_to_d(p) for p in patch_set]
print(json.dumps(o))
