#!/usr/bin/env python3

import json
import sys
import subprocess


def main():
    d=json.load(sys.stdin)
    a = []
    for e in d:
        p = subprocess.run(e, capture_output=True)
        a.append({
            "stdout": p.stdout.decode("utf-8"),
            "stderr": p.stderr.decode("utf-8"),
            "returnCode": p.returncode
        })

    print(json.dumps(a))


if __name__ == "__main__":
    main()
