#!/usr/bin/env bash

set -eou pipefail

if [[ "$#" -gt "1" ]]; then
    echo "Usage: $0 [FILE]"
    exit 1
fi

if [[ "$#" == "0" ]]; then
    jq -S '.'
    exit 0
fi

FILE="$1"
if [[ "$FILE" == "-" ]]; then
    jq -S '.'
elif [[ ! -f "$FILE" ]]; then
    echo "$FILE does not exist"
    exit 1
elif ! jq '.' "$FILE" > /dev/null; then
    echo "json is invalid, aborting"
    exit 1
elif [[ -z "$(jq '.' "$FILE")" ]]; then
    echo "jq output returned nothing, aborting"
    exit 1
else
    TMP="$(mktemp)"
    jq -S '.' "$FILE" > "$TMP"
    mv "$TMP" "$FILE"
fi
