#!/usr/bin/env python3

import json
import sys


def main():
    rows = json.load(sys.stdin)
    delimiter = sys.argv[1]
    for row in rows:
        print(delimiter.join([str(e) for e in row]))


if __name__ == "__main__":
    main()
