#!/usr/bin/env python3

import json
import sys
import yaml


def main():
    data = json.load(sys.stdin)
    yaml_s = yaml.dump(data, default_flow_style=False)
    print(yaml_s, end='')


if __name__ == "__main__":
    main()
