#!/usr/bin/env python3

import csv
import json
import sys

def main():
    rows = json.load(sys.stdin)
    delimiter = sys.argv[1]
    for row in rows:
        print(delimiter.join(row))
    exit(0)

if __name__ == "__main__":
    main()
