#!/usr/bin/env bash

pylint3 \
csv-to-json \
dsv-to-json \
generate-json-diff-results \
generate-test-results \
json-sql \
json-to-csv \
json-to-dsv \
json-to-logfmt \
json-to-xml \
json-to-yaml \
logfmt-to-json \
python-to-json-ast \
xml-to-json \
yaml-to-json \
2>&1 | grep -v "Using config file"
go vet
