#!/usr/bin/env bash

set -euo pipefail

# As the rest of the test program uses json diff, we cannot test json diff using json diff.
./run-json-diff-tests

TEST_FILE=test_data/tests.json
TMP_FILE=$(mktemp)
cat ${TEST_FILE} | ./generate-test-results > ${TMP_FILE}
./json-diff ${TMP_FILE} ${TEST_FILE} | ./json-empty
rm ${TMP_FILE}
