#!/usr/bin/env bash

go fmt json-diff.go &
go fmt json-empty-array.go &
autopep8 -i csv-to-json &
autopep8 -i dsv-to-json &
autopep8 -i generate-json-diff-results &
autopep8 -i generate-test-results &
autopep8 -i json-make-schema &
autopep8 -i json-sql &
autopep8 -i json-to-csv &
autopep8 -i json-to-dsv &
autopep8 -i json-to-logfmt &
autopep8 -i json-to-xml &
autopep8 -i json-to-yaml &
autopep8 -i logfmt-to-json &
autopep8 -i python-to-json-ast &
autopep8 -i xml-to-json &
autopep8 -i yaml-to-json &
wait
