#!/usr/bin/env python3

import json
import sys
import click

@click.command()
@click.help_option()
def main():
    """Converts input data to JSON format"""
    data = list(sys.stdin.buffer.read())
    print(json.dumps(data))

if __name__ == "__main__":
    main()
