#!/usr/bin/env python3

import json
import sys


def main():
    delimiter = sys.argv[1]
    if delimiter == "-z":
        delimiter = chr(0)
    lines = sys.stdin.readlines()
    cells = [l.strip("\n").split(delimiter) for l in lines]

    print(json.dumps(cells))


if __name__ == "__main__":
    main()
