#!/usr/bin/env python3

import json
import sys

import logfmt


def main():
    d = json.load(sys.stdin)
    if type(d) != list:
        raise Exception("Only lists can be converted to logfmt")

    for l in logfmt.format(*d):
        print(l)


if __name__ == "__main__":
    main()
